export enum ProfileReportReason {
  // Fraud
  IMPERSONATION = 'IMPERSONATION',
  FRAUD_SOMETHING_ELSE = 'FRAUD_SOMETHING_ELSE',

  // Spam
  REPETITIVE = 'REPETITIVE',
  SPAM_SOMETHING_ELSE = 'SPAM_SOMETHING_ELSE',
}
