import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import 'simpledotcss/simple.min.css';
import './globals.css';
import { Suspense } from 'react';
import { Web3Providers } from './Web3Providers';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Next.js - Lens Client Integration',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Web3Providers>
          <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
        </Web3Providers>
      </body>
    </html>
  );
}
